# Generated by Django 5.1.2 on 2024-10-31 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
