# Generated by Django 5.1.2 on 2024-11-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_otp_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp_time',
            new_name='otp_created_time',
        ),
        migrations.AddField(
            model_name='user',
            name='otp_expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
