# Generated by Django 5.1.2 on 2024-11-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_otp_time_user_otp_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_otp_expired',
            field=models.BooleanField(default=False),
        ),
    ]
