# Generated by Django 5.1.2 on 2024-11-01 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_is_otp_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
