# Generated by Django 5.1.2 on 2024-11-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_user_otp_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_otp_expired',
        ),
    ]
